[View in Colaboratory](https://colab.research.google.com/github/ArnabG99/NumpyJupyterNotekook/blob/master/Numpy_1.ipynb)

***Numpy***
---
Numpy stands for numerical pyhon.

**What is numpy?**

NumPy is a library for the Python programming language which provide support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.



In [0]:
import numpy as np #Calling numpy library

Creating arrays with numpy.

In [10]:
a = np.array([1,2,3])   #single dimensional or order 1
b = np.array([(1,2,3),  #two dimensional or ordr 2 
             (4,5,6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


Creating an array of certain range.

In [11]:
a = np.arange(10) # creating an array having 0 to 9
print(a)

[0 1 2 3 4 5 6 7 8 9]


Dimension, shape, type of arrays.

In [18]:
a = np.array([(1,2,3),
              (4,5,6),
              (7,8,9)])

print(a.ndim)   #Dimension
print(a.shape)  #Shape
print(type(a))  #Type

2
(3, 3)
<class 'numpy.ndarray'>


In [40]:
a = np.array([(1,2,3,4),
              (5,6,7,8),
              (9,1,2,3)])

print(a)
b = a.reshape(4,3)
print(b)

print(a[0,0]) # 1
print(a[1,2]) # 7

print(a[0:2,2])
print(a[0:,1])
print(a[0:,1:])



[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
1
7
[3 7]
[2 6 1]
[[2 3 4]
 [6 7 8]
 [1 2 3]]
