[View in Colaboratory](https://colab.research.google.com/github/ArnabG99/NumpyJupyterNotekook/blob/master/Numpy_1.ipynb)

***Numpy***
---
Numpy stands for numerical pyhon.

**What is numpy?**

NumPy is a library for the Python programming language which provide support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.



In [0]:
import numpy as np #Calling numpy library

Creating arrays with numpy.

In [8]:
a = np.array([1,2,3])   #single dimensional or order 1
b = np.array([(1,2,3),  #two dimensional or ordr 2 
             (4,5,6)])

print(a)
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]
